config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'events#index'

  resources :events, only: %i[index show new create edit update] do
    resources :attendances, only: %i[create destroy]
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :user, uniqueness: { scope: :event, message: 'You are already part of the event!' }
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :host, class_name: 'User'
  has_many :attendances, dependent: :destroy
  has_many :attendees, through: :attendances, source: :user

  validates :event_name, presence: true
  validates :location, presence: true
  validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :hosted_events, class_name: 'Event', foreign_key: 'host_id', dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :attend_events, through: :attendances, source: :event

  validates :username, presence: true, uniqueness: true
  validates :display_name, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/Users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    added_attrs = [:username, :display_name]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    added_attrs = [:username, :display_name]
    devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!

  def create
    user = current_user
    @events = Event.all
    event = Event.find(params[:event_id])
    attendance = event.attendances.new(user: user)
    if attendance.save
      redirect_to user_path(current_user.id), notice: 'You have successfully joined the event!'
    else
      flash.now[:errors] = attendance.errors.full_messages
      render 'events/index', status: :unprocessable_entity, locals: { events: @events }
    end
  end

  def destroy
    Attendance.find(params[:id]).destroy
    redirect_to events_path, notice: 'Sorry to see you go!'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @user = @event.host
  end

  def new
    @user = current_user
    @event = Event.new
  end

  def create
    @user = current_user
    @event = @user.hosted_events.build(event_params)
    if @event.save
      @event.attendances.create(user: current_user)
      redirect_to root_url
    else
      flash.now[:errors] = @event.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      flash.now[:errors] = @event.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.require(:event).permit(:event_name, :description, :location, :date, :host_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @hosted_events = @user.hosted_events
    @attend_events = @user.attend_events - @hosted_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.erb
<h3>
  <div><%= link_to "#{event.event_name}", event_path(event.id) %></div>
</h3>
<div><%= event.description %></div>
<em>
  <div><%= "Event Host: #{event.host.display_name}" %></div>
  <div><%= event.location %></div>
  <div><%= event.date %></div>
</em>

<% if local_assigns[:show_join] %>
  <div><%= link_to "Join Event!", event_attendances_path(event.id), data: { turbo_method: :post } %></div>
  <% if user_signed_in? %>
    <%# Prevents owner of event from not going %>
    <% if current_user.attend_event_ids.include?(event.id) && !current_user.hosted_event_ids.include?(event.id) %>
      <div><%= link_to "I'm not going anymore", event_attendance_path(event_id: event.id, id: Attendance.find_by(event_id: event.id, user_id: current_user.id).id), data: { turbo_method: :delete } %></div>
    <% end %>
  <% end %>
<% end %>

app/views/events/_form.html.erb
<%= form_with model: @event do |form| %>
  <div>
    <%= form.label :event_name, "Event Name" %>
    <%= form.text_field :event_name %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>
  <div>
    <%= form.label :date %>
    <%= form.datetime_field :date, min: Date.new(1500, 01, 01), max: Date.new(2100, 12, 31) %>
  </div>
  <div><%= form.submit "Submit" %></div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render "form" %>

app/views/events/index.html.erb
<h1> Finde Events in deiner Nähe - eventim </h1>

<div>
    <%if @events.empty? %>
        <%= 'Es sind keine Events registriert.'%>
  <% else %>
    <%= render partial: "events/event", collection: @events, locals: {show_join: true} %>
  <% end %>
</div>

<h4><%= link_to "Create a New Event!", new_event_path %></h4>

app/views/events/new.html.erb
<h1><%= "Creating #{@user.display_name}'s new event..." %></h1>

<%= render "form" %>

app/views/events/show.html.erb
<h1> <%= "#{@event.event_name}" %></h1>

<div>
    <div>
        <%= "Host: " %>
        <%= link_to "#{@user.display_name}", user_path(@user.id) %>
    </div>
    <div><%= @event.description %></div>
    <div><%= @event.location %></div>
    <div><%= @event.date %></div>
</div>

<% if current_user == @user %>
    <div><%= link_to "Edit Event", edit_event_path%></div>
<% else %>
    <div><%= link_to "Join!", event_attendances_path(@event.id), data: {turbo_method: :post} %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <div>
        <%= link_to "Homepage", root_url %>
        <%= link_to "Login", new_user_session_path %>
        <%= link_to "Signup", new_user_registration_path %>
      </div>
      <div>
        <% if user_signed_in? %>
          <%= "Current User: " %>
          <%= link_to "#{current_user.display_name}", user_path(current_user.id) %>
          <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %>
        <% end %>
      </div>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if flash.now[:errors] %>
      <% flash[:errors].each do |msg| %>
        <div><%= msg %></div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1><%= "#{@user.display_name}'s Profile" %></h1>
<% if @user == current_user %>
  <%= link_to "Edit Profile", edit_user_registration_path %>
<% end %>
<div>
  <h2><%= "About" %></h2>
  <div><%= "Name: #{@user.display_name}" %></div>
  <div><%= "Username: #{@user.username}" %></div>
  <div><%= "Email: #{@user.email}" %></div>
</div>
<div>
  <h2><%= "Hosting:" %></h2>
  <% if @hosted_events.none? %>
    <%= "#{@user.display_name} has no hosting plans!" %>
  <% else %>
    <%= render partial: "events/event", collection: @hosted_events, locals: {show_join: true} %>
  <% end %>
</div>
<div>
  <h2><%= "Attending:" %></h2>
  <% if @attend_events.none? %>
    <%= "#{@user.display_name} is not attending any events!" %>
  <% else %>
    <%= render partial: "events/event", collection: @attend_events, locals: {show_join: true} %>
  <% end %>
</div>